version: "3"
services:
  mongo2:
    image: mongo
    ports:
      - 30002:27017
    volumes: 
      - mongo2:/data/db
    command: mongod --replSet mongoset 

  mongo3:
    image: "mongo"
    ports:
      - "30003:27017"
    volumes:
      - mongo3:/data/db
    command: mongod --replSet mongoset 

volumes: 
  mongo2:
  mongo3:
